apiVersion: "installers.tmc.cloud.vmware.com/v1alpha1"
kind: "AgentConfig"
metadata:
  name: "tmc-agent-config"
  namespace: "svc-tmc-c8"
spec:
  caCerts: |-
    -----BEGIN CERTIFICATE-----
    MIIEGTCCAwGgAwIBAgIUfQ05NpJKPiiR4atK3c4uJCuqHqgwDQYJKoZIhvcNAQEL
    BQAwgZsxCzAJBgNVBAYTAklUMQ4wDAYDVQQIDAVJdGFseTENMAsGA1UEBwwEcm9t
    ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMSMwIQYDVQQDDBpo
    Mm8tNC0yMzEzMC5oMm8udm13YXJlLmNvbTElMCMGCSqGSIb3DQEJARYWY3B1bGNp
    bmkyMDAzQGdtYWlsLmNvbTAeFw0yNDAyMjcxODIwMzRaFw0yOTAyMjUxODIwMzRa
    MIGbMQswCQYDVQQGEwJJVDEOMAwGA1UECAwFSXRhbHkxDTALBgNVBAcMBHJvbWUx
    ITAfBgNVBAoMGEludGVybmV0IFdpZGdpdHMgUHR5IEx0ZDEjMCEGA1UEAwwaaDJv
    LTQtMjMxMzAuaDJvLnZtd2FyZS5jb20xJTAjBgkqhkiG9w0BCQEWFmNwdWxjaW5p
    MjAwM0BnbWFpbC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCK
    2F+Iqx7u3XduwnZbiG17BWKfiaSkzOElAMN/4sf933+jZXzlQD3/3uAZ961KMDz1
    FKhctlGyRAQIrYwOrUb4YwnjZEL5QnoVyVf6PWvFGZRqk2nULCeuwRxnVFrRaAhk
    jOUiIEfL8DnoVDr0NostL9RJ6WvQdjn5knxfNRKDN0mrfYLRND6Wlz2VaOVFmfF8
    k83iNfsNfOuasegqSLWPMLZOCQeAvlpacJe3VW1pLlyByVSzRs8r9NISXF6GABGY
    vy3Ir2tiMfEtjrs1kzbg31dZRuT+NU2hieNpBOjarLWaHxO803MLsVx/ukPylpYl
    kSdzuUALtBsFUFHuOsIDAgMBAAGjUzBRMB0GA1UdDgQWBBTMPnIibKv6XIyTHB2C
    Mc3eSFTq0jAfBgNVHSMEGDAWgBTMPnIibKv6XIyTHB2CMc3eSFTq0jAPBgNVHRMB
    Af8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQBgInsy4Uffua4uxBnKXUm6XHlx
    Mp65Hh5lheya9DxkatDThaE5mNFnmVF8jQWUvpHbBhqMyTN2+9zMt9ojuokYOMzy
    qo40f2Qnd1sPUVPXWnrooDirknrHYgG2SWDV5unnveU5zxuCmpY7eUUOqLRZ1ksR
    KiTP4YbweyqrrD2vJ6khTkwWx1MKHFeMhPstZGdFokzWu1eUVWeFSfeeUnv5vN3D
    F8W7ulNx4A7wzNtUXg7/4GaqTcwIKEbMXUMpUxS5xqRbOYRX0KEXXtkm2ka0+GPG
    AVyM24SWvdw5ZG9nfo9vXwB4glF3fSa7KJlQh2NsWHHKOH7BNPtzrAxtSJRv
    -----END CERTIFICATE-----
  allowedHostNames:
    - "tmc.h2o-4-23130.h2o.vmware.com"