apiVersion: v1      # apiVersion: this is the version of the API used by the cluster. 
kind: Pod           
metadata:           # Metadata: here we can define data about the object we are about to create.
  name: webserver   # In this example, we only provide the name of the pod. But you can provide other details like the namespace.
spec:               #The spec part defines the characteristics that a given Kubernetes object should have. 
  containers:
  - name: webserver  # The name that this container will have.
    image: nginx:latest # The image on which it is based.
    ports:               # The port(s) that will be open.
    - containerPort: 80
