apiVersion: installers.tmc.cloud.vmware.com/v1alpha1
kind: AgentInstall
metadata:
  name: tmc-agent-installer-config
  namespace: svc-tmc-c8
spec:
  operation: INSTALL
  registrationLink: https://tmc.h2o-4-23130.h2o.vmware.com/installer?id=da773b1094fbc78edf93ff4c2f1f5fe6ed2bf392d04d6b28a70bfcf19b5e1472&source=registration&type=tkgs