apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tmcsm-cluster
  namespace: control-plane
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-2xlarge
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
    nodePools:
    - name: tkg-cluster-nodeool-1
      replicas: 5
      vmClass: best-effort-4xlarge
      storageClass: vc01cl01-t0compute
      tkr:
        reference:
          name: v1.23.8---vmware.3-tkg.1
      volumes:
      - capacity:
          storage: 60Gi
        mountPath: /var/lib/containerd
        name: containerd
  settings:
    network:
      trust:
        additionalTrustedCAs:
          - name: sm-harbor
            data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURLVENDQWhHZ0F3SUJBZ0lSQU9nTGthRzZkVUZZWElKM25RL0ZrQW93RFFZSktvWklodmNOQVFFTEJRQXcKRkRFU01CQUdBMVVFQXhNSlNHRnlZbTl5SUVOQk1CNFhEVEkwTURJeU5qSXdORFUwTlZvWERUTTBNREl5TXpJdwpORFUwTlZvd0ZERVNNQkFHQTFVRUF4TUpTR0Z5WW05eUlFTkJNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DCkFROEFNSUlCQ2dLQ0FRRUFybVNuZnNPeGdqYVIweHRBK3gwM0dCM1JGemhZVkU2QjA5UXpBaGtjampidWdRTzUKSzhiR3hqMDZZTmVzcWJoMmhzZU13d00wbk9lU21MRzY4emtWa1VTL0VWY3BKaStuaWZDVlhVWHpVQ0hRajJSRwppK2NhKzdGd283STh0djdUdnUwT3gyZVFmaEg2NDVYYlM2VFNmMU5DcUh0WmlnRzVrNVlyM3RwUVgrYllXZHpvCjdXRlMvenJ4VHJnWHptaDRZUzJxOGlIRXpBVjNQQ2cvQ0FYUDE4bFMyTW54RjJLVFZ3YVNxWktwa3dqdUJmelgKSmNxaXltTFZzZXR2WGtqYWpVVW9idktVU0VuZE4ySkk2ZXczTFZUWTV3U1pNOVhPTzNZSENsNEFJdnQ2NXF5Sgp2ZnZWYjFNY3NrS1BkaUtDZ3QwTG1JMlJLTEdPOGhHRVpQSVZXUUlEQVFBQm8zWXdkREFPQmdOVkhROEJBZjhFCkJBTUNBZ1F3SFFZRFZSMGxCQll3RkFZSUt3WUJCUVVIQXdFR0NDc0dBUVVGQndNQ01BOEdBMVVkRXdFQi93UUYKTUFNQkFmOHdIUVlEVlIwT0JCWUVGTllFc2VldGlYZ3RlU1p6QndVREdGcmI3ZmpzTUJNR0ExVWRFUVFNTUFxQwpDR2hoY21KdmNtTmhNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNHYWpjV0wxUXZTS2J0c3lnZUE4YWhJUjJ4CkxoRUNCUEZqTGREcENmRFNHZVZIeHdHMjJQUkliOCthRnhIOFJYTVBJdUVqOEg5Z1U3ZTJhbU16elJMZFZOZWwKUC9kbXFQRHAzQ0JvWWpjVEFTRnBjUFpjUnVEZkVjT2FHWlZ1U2FRWnlFdFBYalJtcmxxRFhXQjc3dHg0QTRQMwp4bXBJZFVqS2VzOFBmc05iY0ZVUkFuYmdZb3VPdWliUGdKY3B5TUlXR0RYTkZicDBnMDAxYzlJdllra3ZJMVZXCm1PWmlvQjV1MmRsTnlmRDFYbWhrV1F0bU9lZXBBN0tpaitYbHFsTC9mZytlT0tPKzJFRmlOc2pLVzRDNmZudFYKajNqTm5iaWI1K2pKUGlQWkJXaTZUZEFta1dUQTg0TVVVY1A5QXFtbDJMeVdXeGVHck16MWp1czdFdzZICi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      pods:
        cidrBlocks:
        - 100.96.0.0/11
      services:
        cidrBlocks:
        - 100.64.0.0/13
    storage:
      defaultClass: vc01cl01-t0compute