apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: cluster-default
  namespace: tmcsm
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["198.51.100.0/12"]
    pods:
      cidrBlocks: ["192.0.2.0/16"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.24.9---vmware.1-tkg.4
    controlPlane:
      replicas: 3
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 3
    variables:
      - name: vmClass
        value: best-effort-4xlarge
      - name: storageClass
        value: vc01cl01-t0compute
      - name: defaultStorageClass
        value: vc01cl01-t0compute
      - name: trust
        value:
          additionalTrustedCAs:
          - name: additional-ca-1
      - name: controlPlaneVolumes
        value:
          - name: containerd
            mountPath: /var/lib/containerd
            storageClass: vc01cl01-t0compute
            capacity:
              storage: 60Gi 
